# -*- coding: utf-8 -*-
"""create_database.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h0aQpz091OfxLTkQoDKuLPzwyyEKxdnD
"""

import sqlite3

# Connect to SQLite database
conn = sqlite3.connect('realestate.db')

# Create a cursor object using the cursor method
cursor = conn.cursor()

# Create table with appropriate data types
cursor.execute('''
CREATE TABLE IF NOT EXISTS properties (
    date TEXT,
    price INTEGER,
    bedrooms INTEGER,
    bathrooms REAL,
    sqft_living INTEGER,
    sqft_lot INTEGER,
    floors REAL,
    waterfront INTEGER,
    view INTEGER,
    condition INTEGER,
    sqft_above INTEGER,
    sqft_basement INTEGER,
    yr_built INTEGER,
    yr_renovated INTEGER,
    street TEXT,
    city TEXT,
    statezip TEXT,
    country TEXT
)
''')

# Commit the changes and close the connection
conn.commit()
conn.close()