# -*- coding: utf-8 -*-
"""load.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CeTzlJCCX5ihkF6bwzLhIbv82HkfBYJH
"""

import pandas as pd
import sqlite3

# Load data from CSV file
data = pd.read_csv('~/my_project/data/houseprice/data.csv')

# Connect to the SQLite database
conn = sqlite3.connect('realestate.db')

# Insert data into the database
data.to_sql('properties', conn, if_exists='append', index=False, method='multi')

# Commit changes and close the connection
conn.commit()
conn.close()