# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mf54WaoygUVJy2XolksVBzrwLwa5jl7c
"""
import pandas as pd
import sqlite3
# Connect to the SQLite database
conn = sqlite3.connect('realestate.db')

# Query the database
query = "SELECT * FROM properties LIMIT 5;"
df = pd.read_sql_query(query, conn)

# Display the result
print(df)

# Close the connection
conn.close()